language: node_js
node_js:
- '0.10'
- '0.12'
deploy:
  provider: npm
  email: adriaan.callaerts@gmail.com
  api_key:
    secure: c2WJgOHckWhVCOxqhaRZ2Rtu3Z8ykoSRif1B1PiJ8HcpC0TmHTAwGjZiolMzt3zj4Cv2Qyp91w1EIKEo4e69EPsGX22RDWME6bh2nnXzDUIZ6XUi6ylb4iy4fao2Vlg83+SbmiIPg5PZJfnTcpqFw0BvK989vk920zFyk6ZTHWs=
  on:
    tags: true
    repo: capaj/require-globify
    all_branches: true
